name: excelapp
description: The Official App of the tech fest of Govt. Model Engineering College.
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # cupertino_icons: ^0.1.2
  # Add packages below -- App size is a concern

  # Backend
  path: ^1.6.4
  shared_preferences: ^0.5.6+3
  cached_network_image: ^2.0.0
  connectivity: ^0.4.8+2
  intl: ^0.16.1
  google_sign_in: ^4.5.1
  hive: ^1.4.2
  social_share: ^2.0.5
 
  # UI
  shimmer: ^1.1.1
  flutter_spinkit: ^4.1.2
  searchable_dropdown: ^1.1.3
  url_launcher: ^5.4.2
  carousel_slider: ^1.4.1
  introduction_screen: ^1.0.8
  font_awesome_flutter: ^8.4.0
  image_picker: ^0.6.7+7
  fluttertoast: ^7.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/min.png"

flutter:

  uses-material-design: true

  assets:
  - assets/
  - assets/introScreen/page2.jpg
  - assets/introScreen/page3.jpg
  - assets/introScreen/page4.jpg
  - assets/campusAmbassador/refer.png
  - assets/campusAmbassador/higher.png

  fonts:
      - family: poppins
        fonts:
          - asset: assets/fonts/Poppins-Regular.ttf
          - asset: assets/fonts/Poppins-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/Poppins-Bold.ttf
            weight: 700
          - asset: assets/fonts/Poppins-ExtraBold.ttf
            weight: 800
      - family: quicksand
        fonts:
          - asset: assets/fonts/Quicksand-Regular.ttf
          - asset: assets/fonts/Quicksand-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/Quicksand-Bold.ttf
            weight: 700
          - asset: assets/fonts/Quicksand-Light.ttf
            weight: 300
