name: excelapp
description: The Official App of the tech fest of Govt. Model Engineering College.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # cupertino_icons: ^0.1.2
  # Add packages below -- App size is a concern
  flutter_auth0: ^0.5.0
  sqflite: ^1.3.0
  path: ^1.6.4
  shared_preferences: ^0.5.6+3
  cached_network_image: ^2.0.0
  url_launcher: ^5.4.2
  carousel_slider: ^1.4.1
  # sticky_headers: ^0.1.8+1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  # assets:
  #  - assets/kryptos.jpg
  #  - assets/lost.jpg


  fonts:
      - family: poppins
        fonts:
          - asset: assets/fonts/Poppins-Regular.ttf
          - asset: assets/fonts/Poppins-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/Poppins-Bold.ttf
            weight: 700
          - asset: assets/fonts/Poppins-ExtraBold.ttf
            weight: 800
      - family: quicksand
        fonts:
          - asset: assets/fonts/Quicksand-Regular.ttf
          - asset: assets/fonts/Quicksand-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/Quicksand-Bold.ttf
            weight: 700
          - asset: assets/fonts/Quicksand-Light.ttf
            weight: 300
